apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
spec:
  project: arc
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
#    targetRevision: 0.11.0
    targetRevision: 0.10.1
    helm:
      values: |
        githubConfigUrl: "https://github.com/air-hand/k8s-playground"
        githubConfigSecret: gh-secret
        runnerScaleSetName: "k8s-playground-runners"
        controllerServiceAccount:
          name: arc-controller-gha-rs-controller
          namespace: arc-system
        template:
          spec:
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:latest
                command: ["/home/runner/run.sh"]
                resources:
                  requests:
                    cpu: 500m
                    memory: 2Gi
                  limits:
                    cpu: 500m
                    memory: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
