apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: arc
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: 0.12.1
    helm:
      values: |
        githubConfigUrl: "https://github.com/air-hand/k8s-playground"
        githubConfigSecret: gh-secret
        runnerScaleSetName: "k8s-playground-runners"
        controllerServiceAccount:
          name: arc-controller-gha-rs-controller
          namespace: arc-system
        template:
          spec:
            #initContainers:
            #  - name: runner-init
            #    image: busybox:stable
            #    command: ["/bin/sh", "-c", "sleep 120"]
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:2.326.0
                command: ["/home/runner/run.sh"]
                resources:
                  requests:
                    cpu: 500m
                    memory: 1500m
                  limits:
                    cpu: 500m
                    memory: 1500m
            tolerations:
              - key: "dedicated"
                operator: "Equal"
                value: "runner"
                effect: "NoSchedule"
            nodeSelector:
              k3d-node-role: arc
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
