apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller
  namespace: argocd
spec:
  project: arc
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: 0.12.1
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: false
      selfHeal: true
