apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gh-secret
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws
    kind: SecretStore
  target:
    name: gh-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: dev/mysecret
