apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arc-controller-helm.yaml
  - external-secret.yaml
  - arc-runners-helm.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: nst
      namespace: arc-runners
    unsetOnly: true
