apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-ssh
spec:
  package: xpkg.upbound.io/upbound/provider-ssh:v0.1.0
---
apiVersion: ssh.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: ssh-config
spec:
  credentials:
    source: Secret
    secretRef:
      name: raspberry-ssh-key
      namespace: crossplane-system
      key: ssh_private_key
