apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k3s-secretstore
  namespace: crossplane-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
