apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: raspberry-ssh
  namespace: k3s-setup
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: k3s-secretstore
    kind: SecretStore
  target:
    name: raspberry-ssh-key
    template:
      type: Opaque
  data:
  - secretKey: ssh_private_key
    remoteRef:
      key: dev/raspi/ssh
