apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - provider-aws.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: nst
      namespace: crossplane-system
    unsetOnly: true