apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
#- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.15/manifests/install.yaml
- application-set.yaml
- projects.yaml
patches:
- path: argocd-patches.yaml
transformers:
- |-
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: nst
    namespace: argocd
  unsetOnly: true
