apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-operator-helm.yaml
  - secret-store.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: nst
      namespace: secret-operator
    unsetOnly: true