apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.14.0
  destination:
    server: https://kubernetes.default.svc
    namespace: secret-operator
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
