---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-model-pv
  labels:
    volume: ollama-model
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /mnt/data/volume-ollama
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-model-pvc
spec:
  storageClassName: local
  selector:
    matchLabels:
      volume: ollama-model
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
