apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: deepseek
spec:
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
