---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-pv
  labels:
    volume: open-webui
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data/volume-webui
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
spec:
  storageClassName: local
  selector:
    matchLabels:
      volume: open-webui
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
