# docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: deepseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "host.docker.internal"
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:0.5.7
          env:
            - name: WEBUI_AUTH
              value: "False"
            - name: OLLAMA_BASE_URL
              value: http://ollama.deepseek.svc.cluster.local:11434
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/backend/data
              name: open-webui-data
      volumes:
        - name: open-webui-data
          persistentVolumeClaim:
            claimName: open-webui-pvc
