---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deepseek-pv
  labels:
    volume: deepseek
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /mnt/data/volume
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepseek-pvc
spec:
  storageClassName: local
  selector:
    matchLabels:
      volume: deepseek
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
