name: "Hello self-hosted runner"

on:
  pull_request:
    branches:
      - main
#  schedule:
#    - cron: "5 */2 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  hello-world:
    runs-on: k8s-playground-runners
    strategy:
      fail-fast: false
      matrix:
#        input: [1, 2, 3, 4, 5]
        input: [1, 2]
    steps:
      - name: Hello world
        run: |
          echo "Hello world ${INPUT}"
        env:
          INPUT: ${{ matrix.input }}
      - name: debug memory limits
        run: |
          echo "=== System Info ==="
          uname -a
          echo "=== Memory Info ==="
          free -h
          echo "=== Swap Info ==="
          cat /proc/swaps
          echo "=== cgroup version ==="
          if [ -f /sys/fs/cgroup/cgroup.controllers ]; then
            echo "cgroup v2"
            cat /sys/fs/cgroup/memory.max 2>/dev/null || echo "no memory.max"
          else
            echo "cgroup v1"
            cat /sys/fs/cgroup/memory/memory.limit_in_bytes 2>/dev/null || echo "no limit file"
          fi
          echo "=== Process limits ==="
          cat /proc/self/cgroup
          echo "=== Container limits ==="
          cat /proc/meminfo | grep -E "(MemTotal|MemAvailable)"
      - name: install stress-ng
        run: |
          sudo apt-get update
          sudo apt-get install -y stress-ng
      - name: stress-ng
        run: |
          # OOM killed with 1GB memory runner
          stress-ng --vm 4 --vm-bytes 4192M --timeout 60s
