name: "Hello self-hosted runner"

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  hello-world:
    runs-on: k8s-playground-runners
    steps:
      - name: Hello world
        run: echo "Hello world"
