name: "Hello self-hosted runner"

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *" # test for every 10 minutes
  workflow_dispatch:

permissions: {}

jobs:
  hello-world:
    runs-on: k8s-playground-runners
    strategy:
      fail-fast: false
      matrix:
        input: [1, 2, 3, 4, 5]
    steps:
      - name: Hello world
        run: echo "Hello world ${INPUT}"
        env:
          INPUT: ${{ matrix.input }}
