name: "Hello self-hosted runner"

on:
  pull_request:
    branches:
      - main
#  schedule:
#    - cron: "5 */2 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  hello-world:
    runs-on: k8s-playground-runners
    strategy:
      fail-fast: false
      matrix:
#        input: [1, 2, 3, 4, 5]
        input: [1, 2]
    steps:
      - name: Hello world
        run: |
          echo "Hello world ${INPUT}"
        env:
          INPUT: ${{ matrix.input }}
      - name: install stress-ng
        run: |
          sudo apt-get update
          sudo apt-get install -y stress-ng
      - name: stress-ng
        run: |
          # OOM killed with 1GB memory runner
          stress-ng --vm 1 --vm-bytes 1500M --timeout 60s
