apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: test-ssh-connection-master
spec:
  forProvider:
    inventoryInline:
      hosts:
        - name: rasp-111
          vars:
            ansible_host: 192.168.0.111
            ansible_user: pi
            ansible_ssh_private_key_file: /tmp/ansible-ssh-key
    playbookInline:
      - name: Test SSH connection
        hosts: all
        become: yes
        tasks:
          - name: Create a test file
            file:
              path: /tmp/ansible-test-file
              state: touch
              mode: '0644'

          - name: Write to test file
            copy:
              content: "Ansible test successful at {{ ansible_date_time.iso8601 }}"
              dest: /tmp/ansible-test-file
  providerConfigRef:
    name: ansible-provider-config
