apiVersion: ansible.crossplane.io/v1alpha1
kind: Play
metadata:
  name: k3s-worker-setup
  annotations:
    crossplane.io/external-name: k3s-worker-setup
spec:
  forProvider:
    inventory:
      hosts:
        - name: rasp-158
          vars:
            ansible_host: 192.168.0.158
            ansible_user: pi
            ansible_ssh_private_key_file: /tmp/ansible-ssh-key
            k3s_version: ${configmap:k3s-config:version}
            master_ip: 192.168.0.111
            node_token: ${play:k3s-master-setup:k3s_node_token}
    playbook:
      source: ConfigMap
      configMapRef:
        name: ansible-playbooks
        namespace: crossplane-system
        key: install-worker.yaml
  providerConfigRef:
    name: ansible-provider-config
  dependsOn:
    - name: k3s-master-setup
